#!/bin/bash
echo "Test" | xclip 2> /dev/null
if [ $? -eq 127 ] ; then
	echo "Xclip is not installed on your system! Terminating..."
	exit 1
fi
while IFS=";" read name ipa uname pass supass
do
	if [ "$name" = "$1" ] ; then
		servername="$name"
		ipaddress="$ipa"
		username="$uname"
		password="$pass"
		superpass="$supass"
	fi
done < "$DF"
echo -n "$password" | xclip
echo -n "$superpass" | xclip -selection clipboard
ssh "$username@$ipaddress"
