#!/bin/bash
if [ -n "$2" ] ; then
	if [ "$2" != "root" ] ; then
		echo "Invalid argument \"$2\"! Terminating..."
		exit 2
	fi
fi
echo "Test" | expect 2> /dev/null
if [ $? -eq 127 ] ; then
	echo "Expect is not installed on your system! Terminating..."
	exit 1
fi
while IFS=";" read name ipa uname pass supass suc opt
do
	if [ "$name" = "$1" ] ; then
		ipaddress="$ipa"
		username="$uname"
		password="$pass"
		superpass="$supass"
		sucommand="$suc"
		options="$opt"
	fi
done < "$DF"
echo "#/usr/bin/expect -f
trap {
 set rows [stty rows]
 set cols [stty columns]
 stty rows \$rows columns \$cols < \$spawn_out(slave,name)
} WINCH
spawn ssh "$options" -o StrictHostKeyChecking=no $username@$ipaddress
expect \"*assword\"
send -- \"$password\r\"
if {{$2}=={root}} {
	expect \"*\$*\"
	send -- \"$sucommand\r\"
	expect \"*assword\"
	send -- \"$superpass\r\"
}
interact" > /tmp/.Go-to-Server-Winch
expect -f /tmp/.Go-to-Server-Winch
rm /tmp/.Go-to-Server-Winch
