#!/bin/bash
if [ -z "$1" ] ; then
	echo "You haven't specified a configuration file."
	echo "Terminating..."
	exit 1
fi
IFS=$'\n'
file="$1"
settings=( $( < "$file") )
eval "${settings[@]%%#*}"
comments=( "${settings[@]#*## }" )
